packages:
  - apps/*
  - packages/*

catalog:
  react: 19.0.0-rc.0
  react-dom: 19.0.0-rc.0
  next: 15.5.0
  babel-plugin-react-compiler: 1.0.0
  eslint-plugin-react-compiler: npm:eslint-plugin-react-compiler@experimental
  storybook: 8.6.14
  '@storybook/react': 8.6.14
  '@storybook/react-vite': 8.6.14
  '@storybook/cli': 8.6.14
  '@storybook/builder-vite': 8.6.14
  '@storybook/addon-essentials': 8.6.14
  '@storybook/addon-interactions': 8.6.14
  '@mdx-js/loader': 3.1.0
  '@mdx-js/react': 3.1.0
  '@next/mdx': 15.5.0
  '@vanilla-extract/next-plugin': 2.4.14
  '@vanilla-extract/css': 1.15.1
  '@vanilla-extract/vite-plugin': 5.1.1
  vitest: 2.0.5
  jsdom: 25.0.0
  '@testing-library/jest-dom': 6.8.0
  '@testing-library/react': 16.3.0
  '@testing-library/user-event': 14.6.1
  eslint: 9.34.0
  eslint-config-next: 15.5.0
  eslint-config-prettier: 9.1.0
  eslint-plugin-import: 2.29.1
  eslint-plugin-prettier: 5.2.1
  eslint-plugin-react: 7.35.1
  eslint-plugin-react-hooks: 7.0.0
  eslint-plugin-simple-import-sort: 12.1.0
  '@typescript-eslint/eslint-plugin': 8.40.0
  '@typescript-eslint/parser': 8.40.0
  '@eslint/js': 9.3.0
  prettier: 3.3.3
  stylelint: 16.9.0
  stylelint-config-prettier: 9.0.5
  stylelint-config-standard: 36.0.1
  lint-staged: 15.2.10
  '@commitlint/cli': 19.8.1
  '@commitlint/config-conventional': 19.8.1
  typescript: 5.4.5
  '@types/node': 20.17.13
  '@types/react': 19.0.7
  '@types/react-dom': 19.0.3
  '@types/mdx': 2.0.13
  '@types/loadable__component': 5.13.10
  '@types/react-color': 3.0.13
  husky: 9.1.4
  vite: 5.4.21
  '@loadable/component': 5.16.7
  react-color: 2.19.3
  chalk: 5.3.0
  inquirer: 9.2.20
  zx: 8.1.0

ignoredBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver

patchedDependencies:
  tui-grid@4.21.22: patches/tui-grid@4.21.22.patch


# Named catalogs grouped by package kinds for clearer usage with `catalog:<name>`
# You can reference a package inside a named catalog like:
# "react": "catalog:framework"
# which will look up the `react` entry in the `framework` catalog below.
catalogs:
  framework:
    react: 19.0.0-rc.0
    react-dom: 19.0.0-rc.0
    next: 15.5.0

  storybook:
    storybook: 8.6.14
    '@storybook/react': 8.6.14
    '@storybook/react-vite': 8.6.14
    '@storybook/cli': 8.6.14
    '@storybook/builder-vite': 8.6.14
    '@storybook/addon-essentials': 8.6.14
    '@storybook/addon-interactions': 8.6.14

  mdx:
    '@mdx-js/loader': 3.1.0
    '@mdx-js/react': 3.1.0
    '@next/mdx': 15.5.0

  vanilla-extract:
    '@vanilla-extract/next-plugin': 2.4.14
    '@vanilla-extract/css': 1.15.1
    '@vanilla-extract/vite-plugin': 5.1.1

  testing:
    vitest: 2.0.5
    jsdom: 25.0.0
    '@testing-library/jest-dom': 6.8.0
    '@testing-library/react': 16.3.0
    '@testing-library/user-event': 14.6.1

  eslint:
    eslint: 9.34.0
    'eslint-config-next': 15.5.0
    'eslint-config-prettier': 9.1.0
    'eslint-plugin-import': 2.29.1
    'eslint-plugin-prettier': 5.2.1
    'eslint-plugin-react': 7.35.1
    'eslint-plugin-react-hooks': 7.0.0
    'eslint-plugin-simple-import-sort': 12.1.0
    '@typescript-eslint/eslint-plugin': 8.40.0
    '@typescript-eslint/parser': 8.40.0
    '@eslint/js': 9.3.0

  style-and-format:
    prettier: 3.3.3
    stylelint: 16.9.0
    'stylelint-config-prettier': 9.0.5
    'stylelint-config-standard': 36.0.1

  tools:
    lint-staged: 15.2.10
    '@commitlint/cli': 19.8.1
    '@commitlint/config-conventional': 19.8.1
    husky: 9.1.4
    zx: 8.1.0

  types:
    typescript: 5.4.5
    '@types/node': 20.17.13
    '@types/react': 19.0.7
    '@types/react-dom': 19.0.3
    '@types/mdx': 2.0.13
    '@types/loadable__component': 5.13.10
    '@types/react-color': 3.0.13

  utilities:
    vite: 5.4.21
    '@loadable/component': 5.16.7
    react-color: 2.19.3
    chalk: 5.3.0
    inquirer: 9.2.20
    zx: 8.1.0
